from __future__ import annotations

UF_HEADER_ROWS = {
    "PE": 2,
}

UF_EXTRA_MAPPINGS = {
    "AC": {
        "ano_celebracao": "ano",
        "orgao_convenente": "nome_osc",
        "orgao_executor": "nome_osc",
        "objeto": "objeto",
        "termino_da_vigencia": "data_fim",
        "valorprevisto": "valor_total",
        "situacao": "modalidade",
        "numeroconvenio": "id_unico",
    },
    "AP": {
        "Credor": "cnpj",
        "Nome do Credor": "nome_osc",
        "Objeto": "objeto",
        "Valor Total": "valor_total",
        "Data Início": "data_inicio",
        "Data Termino": "data_fim",
        "DATA": "data",
    },
    "BA": {
        "CNPJ_CPF Formatado": "cnpj",
        "cnpj_cpf formatado": "cnpj",
        "nom_razao_social": "nome_osc",
        "val_pago": "valor_total",
        "Município": "municipio",
        "Municipio": "municipio",
        "des_objeto": "objeto",
        "ANO_EXERCICIO_INT": "ano",
    },
    "DF": {
        "anoExercicio": "ano",
        "codigoCredor": "cnpj",
        "nomeCredor": "nome_osc",
        "nomeSubtitulo": "objeto",
        "nomeModalidadeAplicacao": "modalidade",
        "valorObFinal": "valor_total",
        "numeroProcesso": "id_unico",
    },
    "AL": {
        "DATA_TRANSACAO": "data",
        "ANO": "ano",
        "VALOR": "valor_total",
        "BENEFICIADO": "cnpj",
        "DESCRICAO_BENEFICIADO": "nome_osc",
        "DESCRICAO_CONVENIO": "objeto",
        "TIPO_CONVENIO": "modalidade",
        "CONVENIO": "id_unico",
        "DATA_INICIO": "data_inicio",
        "DATA_TERMINO": "data_fim",
    },
    "AM": {
        "Plano de Trabalho": "id_unico",
        "Nº Termo": "id_unico",
        "Objeto": "objeto",
        "CNPJ": "cnpj",
        "Convenente": "nome_osc",
        "Valor do Repasse (R$)": "valor_total",
        "Vigencia": "vigencia",
        "EmendaParlamentar?": "observacoes",
    },
    "ES": {
        "dataPublicacao": "data",
        "cnpjConcedenteConvenente": "cnpj",
        "nomeConcedenteConvenente": "nome_osc",
        "cod": "id_unico",
        "dataInicioVigencia": "data_inicio",
        "dataFimVigencia": "data_fim",
        "datafimvigencia": "data_fim",
        "objetivo": "objeto",
        "objeto": "objeto",
        "valorConcessao": "valor_total",
        "valorTotalAditivos": "valor_repassado",
        "valorContrapartida": "valor_contrapartida",
        "nomeMunicipio": "municipio",
        "codIBGEMunicipio": "cod_municipio",
    },
    "GO": {
        "CNPJ_CONTRATANTE": "cnpj",
        "CODIGO_AQUISICAO": "id_unico",
        "INICIO_VIGENCIA": "data_inicio",
        "FIM_VIGENCIA": "data_fim",
        "OBJETO_AQUISICAO": "objeto",
        "TIPO_AQUISICAO": "modalidade",
        "VALOR_AQUISICAO": "valor_total",
        "ANO_CONTRATO": "ano",
        "RAZAO_SOCIAL_CONTRATADO": "nome_osc",
        "NOME_CONTRATADO": "nome_osc",
    },
    "MT": {
        "CPF/CNPJ Convenente": "cnpj",
        "Número": "id_unico",
        "Início": "data_inicio",
        "Fim": "data_fim",
        "Objeto": "objeto",
        "Valor Total": "valor_total",
        "Valor Transferido": "valor_repassado",
        "Valor Contrapartida": "valor_contrapartida",
        "Situação": "modalidade",
        "Convenente": "nome_osc",
    },
    "PE": {
        "Número Instrumento de Pactuação": "id_unico",
        "Prazo Inicial": "data_inicio",
        "Prazo Final": "data_fim",
        "CNPJ": "cnpj",
        "OS/OSCIP": "nome_osc",
        "Objeto": "objeto",
        "Tipo - Instrumento": "modalidade",
        "Valor Pactuado (R$)": "valor_total",
    },
    "PA": {
        "dt_despesa": "data",
        "ds_sigla_orgao": "nome_osc",
        "vlr_empenho_total": "valor_total",
    },
    "PI": {
        "exercicio": "ano",
        "emissao_data": "data",
        "credor_codigo": "cnpj",
        "credor_titulo": "nome_osc",
        "programa_titulo": "objeto",
        "modalidade_titulo": "modalidade",
        "temp_pago_saldo": "valor_total",
    },
    "PR": {
        "Convenio": "id_unico",
        "Inicio": "data_inicio",
        "Termino": "data_fim",
        "Objeto": "objeto",
        "Situacao": "modalidade",
        "Valor": "valor_total",
        "Beneficiario": "nome_osc",
        "cnpj": "cnpj",
        "nome": "nome_osc",
        "ibge": "cod_municipio",
        "objeto": "objeto",
        "situacao": "modalidade",
        "numero": "id_unico",
        "dt_vigencia_inicio": "data_inicio",
        "dt_vigencia_fim": "data_fim",
        "total_repasses": "valor_total",
    },
    "RN": {
        "Exercicio": "ano",
        "Valor": "valor_total",
        "CnpjBeneficiario": "cnpj",
        "NomeBeneficiario": "nome_osc",
        "Objeto": "objeto",
    },
    "RJ": {
        "NÚMERO": "id_unico",
        "NUMERO": "id_unico",
        "OBJETO": "objeto",
        "PARTÍCIPE": "nome_osc",
        "Partícipe": "nome_osc",
        "CNPJ/MF": "cnpj",
        "VIGÊNCIA INICIAL": "data_inicio",
        "VIGENCIA INICIAL": "data_inicio",
        "TÉRMINO": "data_fim",
        "TERMINO": "data_fim",
        "ANO": "ano",
        "CNPJ/CPF": "cnpj",
        "FAVORECIDO": "nome_osc",
        "NOME DO PROGRAMA": "objeto",
        "TOTAL": "valor_total",
    },
    "RR": {
        "N° Proposta": "id_unico",
        "N° Convênio": "id_unico",
        "Data Início de Vigência Prop.": "data_inicio",
        "Data Fim de Vigência Prop.": "data_fim",
        "Data Início de Vigência Conv.": "data_inicio",
        "Data Fim de Vigência Conv.": "data_fim",
        "Objeto": "objeto",
        "Modalidade": "modalidade",
        "VL Global Proposta": "valor_total",
        "VL Repasse Proposta": "valor_repassado",
        "VL Contrapartida Proposta": "valor_contrapartida",
        "Valor Global": "valor_total",
        "Valor Repasse": "valor_repassado",
        "Valor Contrapartida": "valor_contrapartida",
        "Nome Proponente": "nome_osc",
    },
    "RS": {
        "DataAssinatura": "data",
        "cnpj_convenente": "cnpj",
        "DataInicioVigencia": "data_inicio",
        "DataFimVigencia": "data_fim",
        "Objeto": "objeto",
        "NomeConvenente": "nome_osc",
        "MunicipioConvenente": "municipio",
        "ExercicioConvenio": "ano",
        "TipoTransferencia": "modalidade",
        "ValorConcedente": "valor_total",
    },
    "SE": {
        "dtEmissaoEmpenho": "data",
        "dtLancamentoEmpenho": "data",
        "dtAnoExercicioCtb": "ano",
        "_ano": "ano",
        "_mes": "mes",
        "nuDocumento": "cnpj",
        "nmRazaoSocialPessoa": "nome_osc",
        "nmModalidadeLicitacao": "modalidade",
        "dsObjetoLicitacao": "objeto",
        "vlOriginalEmpenho": "valor_total",
        "vlSolicEmpenho": "valor_total",
        "id": "id_unico",
    },
    "SP": {
        "Objeto": "objeto",
        "Município": "municipio",
        "Entidade": "nome_osc",
        "Início": "data_inicio",
        "Fim": "data_fim",
        "Valor Total": "valor_total",
        "Situação": "modalidade",
        "Cnpj": "cnpj",
    },
    "TO": {
        "Data de Abertura": "data",
        "Situação": "modalidade",
        "Convenente": "nome_osc",
        "Objeto": "objeto",
        "Data de Vigência": "vigencia",
        "Valor do Convênio": "valor_total",
        "Cnpj": "cnpj",
    },
}


def get_uf_mapping(uf: str) -> dict[str, str]:
    return dict(UF_EXTRA_MAPPINGS.get(uf.upper(), {}))
